#!/usr/bin/env node
/**
 * Dashboard write routes require X-Costgate-Dashboard-Token (except UI prefs).
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { createDashboardServer } from "../scripts/dashboard-server.mjs";

function assert(cond, msg) {
  if (!cond) throw new Error(msg);
}

function tempFixture() {
  const dir = join(tmpdir(), `costgate-write-auth-${process.pid}-${Date.now()}`);
  mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "backends.json"), JSON.stringify({ backends: {} }, null, 2));
  writeFileSync(join(dir, "mcp.json"), JSON.stringify({ mcpServers: {} }, null, 2));
  mkdirSync(join(dir, "logs"), { recursive: true });
  return dir;
}

async function startServer(options = {}) {
  const dir = tempFixture();
  const server = createDashboardServer({
    writeToken: options.writeToken,
    dataOptions: {
      logDir: join(dir, "logs"),
      usagePath: join(dir, "usage.json"),
      configPath: join(dir, "backends.json"),
      mcpPath: join(dir, "mcp.json"),
      windowDays: 30,
    },
    controlPaths: {
      configPath: join(dir, "backends.json"),
      mcpPath: join(dir, "mcp.json"),
    },
  });
  await new Promise((resolve, reject) => {
    server.listen(0, "127.0.0.1", (err) => (err ? reject(err) : resolve()));
  });
  const port = server.address().port;
  return {
    server,
    base: `http://127.0.0.1:${port}`,
    close: () => new Promise((resolve) => server.close(resolve)),
  };
}

async function testAutoGeneratedToken() {
  const prev = process.env.COSTGATE_DASHBOARD_TOKEN;
  delete process.env.COSTGATE_DASHBOARD_TOKEN;
  const { server, base, close } = await startServer();
  try {
    assert(typeof server.costgateWriteToken === "string", "auto token string");
    assert(server.costgateWriteToken.length >= 32, "auto token length");
    assert(server.costgateWriteTokenAutoGenerated === true, "auto-generated flag");

    const health = await fetch(`${base}/api/health`).then((r) => r.json());
    assert(health.writes?.token_required === true, "health token_required");

    // UI prefs (locale/timezone) do not require write token.
    const uiOk = await fetch(`${base}/api/ui-settings`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ locale: "ja", timezone: "Asia/Tokyo" }),
    });
    assert(uiOk.ok, `PATCH ui-settings without token ${uiOk.status}`);
    const uiBody = await uiOk.json();
    assert(uiBody.settings?.locale === "ja", "locale patched without token");

    const denied = await fetch(`${base}/api/gate-settings`, {
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ settings: { intent_probe: false } }),
    });
    assert(denied.status === 401, "PATCH gate-settings without token 401");

    const ok = await fetch(`${base}/api/gate-settings`, {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        "X-Costgate-Dashboard-Token": server.costgateWriteToken,
      },
      body: JSON.stringify({ settings: { intent_probe: false } }),
    });
    assert(ok.ok, `PATCH gate-settings with auto token ${ok.status}`);

    console.error("[write-auth] auto-generated token ok");
  } finally {
    if (prev === undefined) delete process.env.COSTGATE_DASHBOARD_TOKEN;
    else process.env.COSTGATE_DASHBOARD_TOKEN = prev;
    await close();
  }
}

async function testExplicitToken() {
  const { server, base, close } = await startServer({ writeToken: "explicit-test-token" });
  try {
    assert(server.costgateWriteToken === "explicit-test-token", "explicit token");
    assert(server.costgateWriteTokenAutoGenerated !== true, "not auto-generated");

    const wrong = await fetch(`${base}/api/gate-settings`, {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        "X-Costgate-Dashboard-Token": "wrong-token",
      },
      body: JSON.stringify({ settings: { intent_probe: false } }),
    });
    assert(wrong.status === 401, "wrong token 401");

    const ok = await fetch(`${base}/api/gate-settings`, {
      method: "PATCH",
      headers: {
        "Content-Type": "application/json",
        "X-Costgate-Dashboard-Token": "explicit-test-token",
      },
      body: JSON.stringify({ settings: { intent_probe: false } }),
    });
    assert(ok.ok, `PATCH with explicit token ${ok.status}`);

    console.error("[write-auth] explicit token ok");
  } finally {
    await close();
  }
}

async function main() {
  await testAutoGeneratedToken();
  await testExplicitToken();
  console.error("[write-auth] all passed");
}

main().catch((e) => {
  console.error("[write-auth] fatal:", e);
  process.exit(1);
});
